pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/4)
=> Add TODO to pom

.gitignore, pom.xml, src/test/java/com/vaadin/ui/formlayout/FormLayoutIT.java
Add component IT test class;
Add dependency;
modify gitignore file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/6)
=> Add Component IT test

pom.xml, src/test/java/com/vaadin/ui/formlayout/FormLayoutIT.java, src/test/java/com/vaadin/ui/formlayout/FormLayoutView.java
+ This is done because otherwise the parent-pom, flow-component, can't
be resolved.
- Remove the main method from demo and IT class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/7)
=> Add Flow repositories to pom.xml

src/test/java/com/vaadin/ui/formlayout/FormLayoutIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/8)
=> WIP- resize the screen for testing

README.md, pom.xml, src/test/java/com/vaadin/ui/formlayout/FormLayoutIT.java, src/test/java/com/vaadin/ui/formlayout/FormLayoutView.java
this is related to ticket vaadin/flow#2795
+add Route title, as it can cause conflict to use default route;
+override getTestPath();
+Update parent and dependency version to SNAPSHOT;
+Update README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/13)
=> prepare to build demo jar

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/14)
=> Update individual component dependency

src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java, src/test/java/com/vaadin/flow/component/formlayout/demo/FormLayoutView.java, src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutIT.java
Part of the package rename #3032
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/19)
=> Rename package com.vaadin.ui to com.vaadin.flow.component

src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/22)
=> Correct import in IT tests

.gitignore, pom.xml, src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java, src/test/java/com/vaadin/flow/component/formlayout/demo/FormLayoutView.java
I have also tried to eliminate the components dependencies, but failed. 
Propose to do this in a separate ticket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/25)
=> Update generated files.

pom.xml, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java, src/test/java/com/vaadin/flow/component/formlayout/demo/FormLayoutView.java
Using new webjars
renaming repository id;
add logging dependency;
remove HtmlImport in component demo file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/27)
=> Update generated file

src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
fix after vaadin/flow#3678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/31)
=> Update generated code

src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutIT.java
resize the window to make the responsive layout work properly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/32)
=> Fix IT test

pom.xml, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/34)
=> Update webjars and generated code

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/36)
=> Fix compilation error

pom.xml, src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutSerializableTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/44)
=> Add serialization test

README.md, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/47)
=> Use 1.1-SNAPSHOT version

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/49)
=> Update webjar to the latest

src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
Fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/54)
=> Provide a default CTOR for FormItem

src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
Fixes #53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/55)
=> Provide a default CTOR for FormItem (#54)

src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/62)
=> Update java wrapper to stable version

src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java, src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
Fixes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/69)
=> Check respnsive steps property value for null

src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java, src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/70)
=> Check respnsive steps property value for null (#69)

src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutSerializableTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/71)
=> Exclude date picker resource from serializable test

src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutSerializableTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/72)
=> Exclude date picker resource from serializable test (#71)

pom.xml, vaadin-form-layout-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/76)
=> plugins + name change

pom.xml, vaadin-form-layout-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/78)
=> Version updates (flow 1.4)

pom.xml, vaadin-form-layout-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/79)
=> Cherry-pick: Version updates (#78)

README.md, vaadin-form-layout-flow-demo/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/80)
=> Add logger dependency and update readme

pom.xml, vaadin-form-layout-flow-demo/pom.xml, vaadin-form-layout-flow-integration-tests/pom.xml, vaadin-form-layout-flow-testbench/pom.xml, vaadin-form-layout-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/82)
=> Update to next minor and Use flow 1.5-SNAPSHOT

vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java, vaadin-form-layout-flow/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutTest.java
Fixes https://github.com/vaadin/flow/issues/2465
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/83)
=> Implement click notifier

vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/88)
=> Return back html imports

vaadin-form-layout-flow-integration-tests/pom.xml, vaadin-form-layout-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/89)
=> Make TB artifactId consistent with other components

pom.xml, vaadin-form-layout-flow-demo/pom.xml, vaadin-form-layout-flow-integration-tests/pom-bower-mode.xml, vaadin-form-layout-flow-testbench/pom.xml, vaadin-form-layout-flow/pom.xml, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/91)
=> Validate NPM and enable bower tests

vaadin-form-layout-flow-demo/src/main/java/com/vaadin/flow/component/formlayout/demo/FormLayoutView.java
the previous steps are too small, user complains that the width never goes below the biggest step
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/94)
=> Make the responsive step more reasonable

README.md, vaadin-form-layout-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/95)
=> Update readme and dependency versions

vaadin-form-layout-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/96)
=> Fix dep version

vaadin-form-layout-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/97)
=> Fix dependencies

vaadin-form-layout-flow-demo/pom.xml
Fixes vaadin/flow#5702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/98)
=> Update bower dependencies to npm

vaadin-form-layout-flow-demo/pom.xml, vaadin-form-layout-flow-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/99)
=> Remove components testbench

vaadin-form-layout-flow/pom.xml, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/101)
=> Bump vaadin-form-layout wc dependency to 2.1.4

vaadin-form-layout-flow/pom.xml, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
Fixes #75
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/103)
=> Bump vaadin-form-layout version to 2.1.6

vaadin-form-layout-flow/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/105)
=> Update WC to 2.1.6

vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-form-layout-flow/107)
=> Do not depend on JSoup

vaadin-form-layout-flow-demo/src/main/java/com/vaadin/flow/component/formlayout/demo/FormLayoutView.java
Fix https://github.com/vaadin/90min-dx-tasks/issues/113
=> Add Description for the setResponsiveSteps method in demo

pom.xml, vaadin-form-layout-flow-demo/pom.xml, vaadin-form-layout-flow-integration-tests/pom-bower-mode.xml, vaadin-form-layout-flow-integration-tests/pom.xml, vaadin-form-layout-flow-testbench/pom.xml, vaadin-form-layout-flow/pom.xml, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormItem.java, vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/GeneratedVaadinFormLayout.java
* Bump snapshot version
* Bump flow-component-base (2.3-SNAPSHOT)
* Bump WC dependency
* Bump webjar dependencies
Part of vaadin/components-team-tasks#534
=> Bump versions for V14.3

vaadin-form-layout-flow-demo/src/main/java/com/vaadin/flow/component/formlayout/demo/FormLayoutView.java, vaadin-form-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutIT.java
Simply layout of the example where binder usage is shown. Move some parts to another example
Fix https://github.com/vaadin/vaadin-form-layout-flow/issues/57
=> Simplify binder example

vaadin-form-layout-flow-demo/src/main/java/com/vaadin/flow/component/formlayout/demo/FormLayoutView.java, vaadin-form-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/formlayout/tests/FormLayoutIT.java
* Simplify binder example
Simply layout of the example where binder usage is shown. Move some parts to another example
Fix https://github.com/vaadin/vaadin-form-layout-flow/issues/57
* Fix white spaces
Cherry-pick from 2.0
=> Simplify binder example (#120)
